server:
  port: 8081
  servlet:
    context-path: /repo

spring:
  main:
    banner-mode: "off"
  mvc:
    favicon:
      enabled: false
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
    # schema: classpath:schema-mysql.sql
    data: classpath:import.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org:
      springframework: INFO
